name: Water Levels
on: [push]
jobs:
  build:
    name: Build and Deploy application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions/setup-node@v2
        with:
          node-version: "16.4.0"
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: make ci-setup
      - run: make ci-test
      - run: make ci-deploy WS_URL=wss://water-levels.fly.dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

